version: "2"

services:

  mongodb:
    container_name: mongo-woodstock
    image: mongo:3.4.2
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=docker
    networks:
      - woodnet

  mongoclient:
    depends_on:
      - mongodb
    container_name: mongo-client
    image: mongoclient/mongoclient:1.4.0
    ports:
      - "3000:3000"
    networks:
      - woodnet

#  db:
#    container_name: postgres-woodstock
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    networks:
#      - woodnet
#    environment:
#      - POSTGRES_USER=sonar
#      - POSTGRES_PASSWORD=sonar
#    volumes:
#      - /docker/woodstock/sonar/postgresql:/var/lib/postgresql
#      - /docker/woodstock/sonar/postgresql_data:/var/lib/postgresql/data
#    privileged: true
#
#  sonarqube:
#    depends_on:
#      - db
#    container_name: sonarqube-woodstock
#    image: sonarqube:latest
#    ports:
#      - "9000:9000"
#    networks:
#      - woodnet
#    environment:
#      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#    volumes:
#      - /docker/woodstock/sonar/sonarqube_conf:/opt/sonarqube/conf
#      - /docker/woodstock/sonar/sonarqube_data:/opt/sonarqube/data
#      - /docker/woodstock/sonar/sonarqube_extensions:/opt/sonarqube/extensions
#      - /docker/woodstock/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#    privileged: true

#  jenkins:
#    container_name: jenkins-woodstock
#    image: jenkins:latest
#    ports:
#      - "8090:8080"
#      - "50000:50000"
#    networks:
#      - woodnet
#    volumes:
#      - /docker/woodstock/jenkins:/var/jenkins_home
#    privileged: true

networks:
  woodnet:
    driver: bridge
