version: "2"

services:

  mongodb:
    container_name: mongo-woodstock
    image: mongo:3.4.2
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=docker
    networks:
      - woodnet

  mongoclient:
    depends_on:
      - mongodb
    container_name: mongoclient-woodstock
    image: mongoclient/mongoclient:1.4.0
    ports:
      - "3000:3000"
    networks:
      - woodnet

  sonardb:
    container_name: sonardb-woodstock
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    networks:
      - woodnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  sonarqube:
    depends_on:
      - sonardb
    container_name: sonarqube-woodstock
    image: sonarqube:6.2-alpine
    ports:
      - "9000:9000"
    networks:
      - woodnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar

  jenkins:
    container_name: jenkins-woodstock
    image: jenkins:2.32.2-alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - woodnet

  portainer:
    container_name: portainer-woodstock
    image: portainer/portainer:latest
    ports:
      - "9010:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - woodnet
    privileged: true

networks:
  woodnet:
    driver: bridge
