version: "2"

services:

  db:
    container_name: postgres-woodstock
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - woodnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
#    volumes:
#      - /opt/docker/woodstock/sonar/postgresql:/var/lib/postgresql
#      - /opt/docker/woodstock/sonar/postgresql_data:/var/lib/postgresql/data

  sonarqube:
    depends_on:
      - db
    container_name: sonarqube-woodstock
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - woodnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#    volumes:
#      - /opt/docker/woodstock/sonar/sonarqube_conf:/opt/sonarqube/conf
#      - /opt/docker/woodstock/sonar/sonarqube_data:/opt/sonarqube/data
#      - /opt/docker/woodstock/sonar/sonarqube_extensions:/opt/sonarqube/extensions
#      - /opt/docker/woodstock/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  mongodb:
    container_name: mongo-woodstock
    image: mongo:latest
    ports:
      - "27017:27017"
#    volumes:
#      - /opt/docker/woodstock/mongo:/data/db

  jenkins:
    container_name: jenkins-woodstock
    image: jenkins:latest
    ports:
      - "8090:8080"
      - "50000:50000"
#    volumes:
#      - /opt/docker/woodstock/jenkins:/var/jenkins_home

networks:
  woodnet:
    driver: bridge
