version: '2'
services:
    woodstock-app:
        image: woodstock
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://woodstock-mysql:3306/woodstock?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    woodstock-mysql:
        extends:
            file: mysql.yml
            service: woodstock-mysql
