version: '2'
services:
    woodstock24-app:
        image: woodstock24
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://woodstock24-postgresql:5432/woodstock24
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    woodstock24-postgresql:
        extends:
            file: postgresql.yml
            service: woodstock24-postgresql
