version: '2'
services:
    woodstock-app:
        image: woodstock
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://woodstock-postgresql:5432/woodstock
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    woodstock-postgresql:
        extends:
            file: postgresql.yml
            service: woodstock-postgresql
