version: "2"

services:

  db:
    container_name: postgres-woodstock
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - woodnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/docker/woodstock/sonar/postgresql:/var/lib/postgresql
      - /opt/docker/woodstock/sonar/postgresql_data:/var/lib/postgresql/data

  sonarqube:
    depends_on:
      - db
    container_name: sonarqube-woodstock
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - woodnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - /opt/docker/woodstock/sonar/sonarqube_conf:/opt/sonarqube/conf
      - /opt/docker/woodstock/sonar/sonarqube_data:/opt/sonarqube/data
      - /opt/docker/woodstock/sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - /opt/docker/woodstock/sonar/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  neo4j:
    container_name: neo4j-woodstock
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - woodnet
    volumes:
      - /opt/docker/woodstock/neo4j:/data

  neo4j-test:
    depends_on:
      - neo4j
    container_name: neo4j-test-woodstock
    image: neo4j:latest
    ports:
      - "7473:7474"
      - "7686:7687"
    networks:
      - woodnet
    volumes:
      - /opt/docker/woodstock/neo4j-test:/data

  jenkins:
    container_name: jenkins-woodstock
    image: jenkins:latest
    ports:
      - "8090:8080"
      - "50000:50000"
    networks:
      - woodnet
    volumes:
      - /opt/docker/woodstock/jenkins:/var/jenkins_home

networks:
  woodnet:
    driver: bridge
